name: Notify on whatsapp

on: 
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  notify-whatsapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send WhatsApp Notification
        uses: KnosTx/whatsapp-notification-action@v1
        with:
          whatsapp_invite_link: "https://chat.whatsapp.com/CBJF14HIs8yGFTOqLzv7TH"
          